//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAppBilling
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int error_message = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int screen_background = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int billing_supported = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int buy_button = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int description = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int item_choices = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int item_name = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int item_quantity = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int log = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int message = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int owned_items = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int payload_edit_button = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int payload_text = 2131099650;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int billing_not_supported = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int edit_payload = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000c
			public const int android_test_canceled = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int android_test_item_unavailable = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int android_test_purchased = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int android_test_refunded = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int billing_not_supported_message = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int billing_not_supported_title = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int buy = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int edit_payload = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int edit_payload_title = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int items_for_sale = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int items_you_own = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int potions = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int recent_transactions = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int restoring_transactions = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int select_item = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int two_handed_sword = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int welcome = 2131034112;
			
			private String()
			{
			}
		}
	}
}
